
import { InvoiceFieldData } from "./InvoiceField";

export const defaultInvoiceFields: InvoiceFieldData[] = [
  {
    id: "invoice-number",
    label: "Invoice Number",
    value: "INV-009876",
    validation: "success",
    validationMessage: "Validated successfully",
    editable: true,
    locked: true,
    confidence: 95,
  },
  {
    id: "invoice-date",
    label: "Invoice Date",
    value: "2024-11-18",
    validation: "success",
    validationMessage: "Validated successfully",
    editable: true,
    locked: false,
    confidence: 90,
  },
  {
    id: "vendor-name",
    label: "Vendor Name",
    value: "Norbridge Supply Inc.",
    validation: "success",
    validationMessage: "Validated successfully",
    editable: true,
    locked: false,
    confidence: 98,
  },
  {
    id: "location",
    label: "Location",
    value: "Alberta – Field Ops",
    validation: "warning",
    validationMessage: "Location format inconsistent with database",
    editable: true,
    locked: false,
    confidence: 80,
  },
  {
    id: "total-amount",
    label: "Total Amount",
    value: "$12,850.00",
    validation: "error",
    validationMessage: "Total doesn't match line items sum ($12,950.00)",
    editable: true,
    locked: false,
    confidence: 75,
  },
  {
    id: "gst-amount",
    label: "GST Amount",
    value: "$642.50",
    validation: "success",
    validationMessage: "Validated successfully",
    editable: true,
    locked: false,
    confidence: 85,
  },
];
