// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getEnvConfig, checkForServiceRoleKey } from '@/utils/envValidation';

/**
 * Supabase Client Configuration
 * 
 * SECURITY NOTE: Environment Variables in Client-Side Code
 * =========================================================
 * 
 * VITE_SUPABASE_PUBLISHABLE_KEY is the Supabase "anon" key.
 * - ✅ SAFE for client-side use (embedded in browser JavaScript)
 * - This key is designed to be publicly visible
 * - Access is controlled by Row Level Security (RLS) policies in your database
 * - This is NOT the service_role key (which must remain server-side only)
 * 
 * All environment variables prefixed with VITE_ are:
 * - Bundled into the client-side JavaScript during build
 * - Visible in the browser's network inspector and source code
 * - Should never contain secret keys or sensitive credentials
 * 
 * For sensitive operations, use Supabase Edge Functions with the service_role key.
 */

// Validate environment variables at startup - fails fast with helpful error message
const config = getEnvConfig();

// Security check: warn if service_role key is accidentally used
checkForServiceRoleKey();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  config.VITE_SUPABASE_URL,
  config.VITE_SUPABASE_PUBLISHABLE_KEY
);